# Generated by Django 5.2.10 on 2026-01-27 18:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brandID', models.AutoField(primary_key=True, serialize=False)),
                ('brandName', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logoURL', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeID', models.AutoField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=20)),
                ('shippingAddress1', models.TextField()),
                ('shippingAddress2', models.TextField()),
                ('shippingAddress3', models.TextField()),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('shippingAddress', models.TextField()),
                ('totalAmount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.customer')),
            ],
            options={
                'ordering': ['-orderDate'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('orderItemID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('paidPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('orderStatusID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Holding', 'Holding'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('orderItemID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='api.orderitem')),
            ],
            options={
                'verbose_name_plural': 'OrderStatuses',
            },
        ),
        migrations.CreateModel(
            name='CancelledItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('cancelledDate', models.DateTimeField(auto_now_add=True)),
                ('orderStatusID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='api.orderstatus')),
            ],
            options={
                'verbose_name_plural': 'CancelledItems',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('availability', models.BooleanField(default=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(auto_now=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.category')),
                ('storeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.store')),
            ],
            options={
                'ordering': ['-createdTime'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.product'),
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('productMediaID', models.AutoField(primary_key=True, serialize=False)),
                ('mediaURL', models.ImageField(upload_to='product_media/')),
                ('mediaType', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('mediaContent', models.TextField(blank=True)),
                ('isPrimary', models.BooleanField(default=False)),
                ('sortedOrder', models.IntegerField(default=0)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.product')),
            ],
            options={
                'ordering': ['sortedOrder'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promotionID', models.AutoField(primary_key=True, serialize=False)),
                ('discountRate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=20)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(auto_now=True)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='api.product')),
            ],
            options={
                'ordering': ['-createdTime'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], default=5)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('orderItemID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.orderitem')),
            ],
            options={
                'ordering': ['-createdDate'],
            },
        ),
        migrations.CreateModel(
            name='StorePhoto',
            fields=[
                ('storePhotoID', models.AutoField(primary_key=True, serialize=False)),
                ('photoURL', models.ImageField(upload_to='store_photos/')),
                ('sortedOrder', models.IntegerField(default=0)),
                ('isPrimary', models.BooleanField(default=False)),
                ('uploadedTime', models.DateTimeField(auto_now_add=True)),
                ('storeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.store')),
            ],
            options={
                'ordering': ['sortedOrder'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendorID', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNo', models.CharField(max_length=20)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='vendor_profiles/')),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='vendorID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='api.vendor'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('addedTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(auto_now=True)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.customer')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.product')),
            ],
            options={
                'unique_together': {('customerID', 'productID')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('vendorID', 'storeName')},
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('wishlistItemID', models.AutoField(primary_key=True, serialize=False)),
                ('addedDate', models.DateTimeField(auto_now_add=True)),
                ('isNotified', models.BooleanField(default=False)),
                ('original_price_at_added', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_rate_at_added', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('price_at_added', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='api.customer')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='api.product')),
            ],
            options={
                'unique_together': {('customerID', 'productID')},
            },
        ),
    ]
