# Generated by Django 5.2.10 on 2026-01-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='firstName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='lastName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
