# Generated by Django 5.2.10 on 2026-02-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vendor_firstname_vendor_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingAddress',
            new_name='shippingAddress1',
        ),
        migrations.AddField(
            model_name='order',
            name='shippingAddress2',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shippingAddress3',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
