# Generated by Django 5.2.10 on 2026-02-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_shippingaddress_order_shippingaddress1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='customer_profiles/'),
        ),
        migrations.AddField(
            model_name='order',
            name='firstName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='lastName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phoneNo',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
