# Generated by Django 5.2.10 on 2026-02-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customer_profileimage_order_firstname_order_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='orderItemID',
        ),
        migrations.AddField(
            model_name='order',
            name='cancellationReason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Holding', 'Holding'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='statusUpdatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='CancelledItem',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
