# Generated by Django 5.2.10 on 2026-02-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_orderstatus_orderitemid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refundRequest',
            field=models.BooleanField(default=False),
        ),
    ]
