# Generated by Django 5.2.10 on 2026-02-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_refund_request_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refundReason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
