# Generated by Django 5.2.10 on 2026-02-26 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_refund_reason_to_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('reviewMediaID', models.AutoField(primary_key=True, serialize=False)),
                ('mediaURL', models.ImageField(upload_to='review_media/')),
                ('mediaType', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('sortedOrder', models.IntegerField(default=0)),
                ('reviewID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.review')),
            ],
            options={
                'ordering': ['sortedOrder'],
            },
        ),
    ]
