# Generated by Django 5.2.10 on 2026-02-28 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationID', models.AutoField(primary_key=True, serialize=False)),
                ('notificationType', models.CharField(choices=[('wishlist_sale', 'Wishlist Item On Sale'), ('order_shipped', 'Order Shipped'), ('order_holding', 'Order On Hold'), ('refund_approved', 'Refund Approved'), ('order_cancelled', 'Order Cancelled'), ('new_order', 'New Order Received'), ('refund_request', 'Refund Requested')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('isRead', models.BooleanField(default=False)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('orderID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.order')),
                ('productID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdTime'],
            },
        ),
    ]
