# Generated by Django 5.2.10 on 2026-03-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='notificationSent',
            field=models.BooleanField(default=False),
        ),
    ]
